apiVersion: v1
kind: Service
metadata:
  name: node-service

spec:
   ports:

     - port: 3000
       targetPort: 80
       nodePort: 30080
       

   selector:
     app: myapp


   type: NodePort   

